### ISSUE TITLE
Main.py: Package management code should not delete packages from non-local package directories.

### ISSUE THREAD

**Issue by richteer** [Halibot/halibot#122]
Offending code in `main.py`:
```python3
        for pkgpath in bot.config["package-path"]:
            path = os.path.join(pkgpath, name)
            if os.path.exists(path):
                shutil.rmtree(path)
                print("Removed '{}' installed to '{}'.".format(name, path))
                success = True
```

If `package-path` included say, `/usr/share/halibot/packages/`, this would also delete that package system-wide. 

Suggestion: remove all package-paths that are not in the subdirectory tree of the current working dir?
Alternative: Restrict deletion from certain reserved directories?
Alternative 2: If multiple are found, prompt user for which to delete from?

**Comment by richteer** [comment]
@sjrct Tagging you here as well, since this behavior was certainly not intended from the original idea of package paths.

**Comment by sjrct** [comment]
Package paths right are dumb when it comes to distinguishing between locally and globally installed repositories. If we distinguish these the this solves itself. Just not removing from subdirectories of the working tree is not a really great fix, I think. There could be some unusual setup where this is expected behavior. What do you think about having a global halibot config that lists global halibot packages?
